import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { poppins } from './fonts';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={poppins.className}>

      <body>{children}</body>
    </html>
  )
}
